import { Request, Response } from 'express';
import { SalarySlipsService } from './salarySlips.service.js';
import { PDFGeneratorService } from '../../core/pdf/PDFGeneratorService.js';
import { ResponseHandler } from '../../core/response/ResponseHandler.js';
import { asyncHandler } from '../../core/errors/asyncHandler.js';

const list = asyncHandler(async (req: Request, res: Response) => {
  const result = await SalarySlipsService.list(req.query as Record<string, unknown>);
  ResponseHandler.success(res, result, 'Salary slips list fetched successfully');
});

const generatePdf = asyncHandler(async (req: Request, res: Response) => {
  const slipData = await SalarySlipsService.generatePdf(req.params.id, req.user!.id) as any;
  
  const html = generateSalarySlipHtml(slipData);
  const filename = `SalarySlip-${slipData.month.replace('-', '_')}.pdf`;
  
  await PDFGeneratorService.generate(html, res, filename);
});

function generateSalarySlipHtml(data: any): string {
  const employeeRows = data.employees.map((emp: any) => `
    <tr>
      <td>${emp.name}</td>
      <td>${emp.employeeCode}</td>
      <td>${emp.department}</td>
      <td>${emp.designation}</td>
      <td style="text-align: right">₹${emp.basicSalary?.toLocaleString()}</td>
      <td style="text-align: right">₹${emp.totalEarnings?.toLocaleString()}</td>
      <td style="text-align: right">₹${emp.totalDeductions?.toLocaleString()}</td>
      <td style="text-align: right; font-weight: bold">₹${emp.netPay?.toLocaleString()}</td>
    </tr>
  `).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #4f46e5; padding-bottom: 20px; }
        .company-name { font-size: 24px; font-weight: bold; color: #4f46e5; }
        .company-address { font-size: 12px; color: #666; margin-top: 5px; }
        .title { font-size: 18px; font-weight: bold; margin: 20px 0; }
        .meta { margin-bottom: 20px; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th { background: #4f46e5; color: white; padding: 10px; text-align: left; }
        td { padding: 8px 10px; border-bottom: 1px solid #eee; }
        .total-row { background: #f5f5f5; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 10px; color: #999; text-align: center; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="company-name">${data.companyName}</div>
        <div class="company-address">${data.companyAddress || ''}</div>
      </div>
      
      <div class="title">Salary Slip - ${data.month}</div>
      
      <div class="meta">
        <strong>Generated Date:</strong> ${new Date(data.generatedDate).toLocaleDateString()}
      </div>
      
      <table>
        <thead>
          <tr>
            <th>Employee Name</th>
            <th>Code</th>
            <th>Department</th>
            <th>Designation</th>
            <th style="text-align: right">Basic Salary</th>
            <th style="text-align: right">Total Earnings</th>
            <th style="text-align: right">Deductions</th>
            <th style="text-align: right">Net Pay</th>
          </tr>
        </thead>
        <tbody>
          ${employeeRows}
        </tbody>
      </table>
      
      <div class="footer">
        Generated by HRMS - Human Resource Management System
      </div>
    </body>
    </html>
  `;
}

export const salarySlipsController = { list, generatePdf };