import { z } from 'zod';

export const createComponentMasterSchema = z.object({
  code: z.string().min(1, 'Code is required').max(20, 'Code must be at most 20 characters'),
  name: z.string().min(1, 'Name is required').max(100, 'Name must be at most 100 characters'),
  type: z.enum(['earning', 'deduction', 'employer-cost']),
  subType: z.enum(['fixed', 'variable', 'reimbursement']).optional(),
  taxable: z.boolean().optional(),
  partOfGross: z.boolean().optional(),
  partOfCtc: z.boolean().optional(),
  pfApplicable: z.boolean().optional(),
  esiApplicable: z.boolean().optional(),
  ptApplicable: z.boolean().optional(),
  bonusApplicable: z.boolean().optional(),
  otBase: z.boolean().optional(),
  lopApplicable: z.boolean().optional(),
  arrearsApplicable: z.boolean().optional(),
  proRataOnJoin: z.boolean().optional(),
  showOnPayslip: z.boolean().optional(),
  calcType: z.enum(['fixed', 'percentage-of-basic', 'percentage-of-gross', 'percentage-of-ctc', 'formula', 'slab']),
  calcValue: z.number().min(0, 'Value must be non-negative'),
  calcReferenceComponent: z.string().optional(),
  frequency: z.enum(['monthly', 'quarterly', 'annual']).optional(),
  effectiveFrom: z.string().or(z.date()),
  effectiveTo: z.string().or(z.date()).optional(),
  isActive: z.boolean().optional(),
  sortOrder: z.number().int().min(0).optional(),
});

export const updateComponentMasterSchema = z.object({
  name: z.string().min(1).max(100).optional(),
  type: z.enum(['earning', 'deduction', 'employer-cost']).optional(),
  subType: z.enum(['fixed', 'variable', 'reimbursement']).optional(),
  taxable: z.boolean().optional(),
  partOfGross: z.boolean().optional(),
  partOfCtc: z.boolean().optional(),
  pfApplicable: z.boolean().optional(),
  esiApplicable: z.boolean().optional(),
  ptApplicable: z.boolean().optional(),
  bonusApplicable: z.boolean().optional(),
  otBase: z.boolean().optional(),
  lopApplicable: z.boolean().optional(),
  arrearsApplicable: z.boolean().optional(),
  proRataOnJoin: z.boolean().optional(),
  showOnPayslip: z.boolean().optional(),
  calcType: z.enum(['fixed', 'percentage-of-basic', 'percentage-of-gross', 'percentage-of-ctc', 'formula', 'slab']).optional(),
  calcValue: z.number().min(0).optional(),
  calcReferenceComponent: z.string().optional(),
  frequency: z.enum(['monthly', 'quarterly', 'annual']).optional(),
  effectiveFrom: z.string().or(z.date()).optional(),
  effectiveTo: z.string().or(z.date()).optional(),
  isActive: z.boolean().optional(),
  sortOrder: z.number().int().min(0).optional(),
});
