import { Request, Response, NextFunction } from 'express';
import { logger } from '../logger/logger.js';

/**
 * Logs each incoming request and its response, tying them together with the
 * requestId generated by the request‑ID middleware.
 */
export function requestLogger(req: Request, res: Response, next: NextFunction): void {
  const start = Date.now();
  const requestId = (req as any).requestId || 'unknown';
  logger.info('Incoming request', { requestId, method: req.method, url: req.originalUrl });

  // When the response finishes, log the outcome
  res.on('finish', () => {
    const durationMs = Date.now() - start;
    const { statusCode } = res;
    logger.info('Request completed', {
      requestId,
      method: req.method,
      url: req.originalUrl,
      statusCode,
      durationMs,
    });
  });

  next();
}
