import { Form, Switch, Typography, Card, Button } from 'antd';
import { KeyOutlined, SaveOutlined } from '@ant-design/icons';

const { Text } = Typography;

interface UserCredentialsSectionProps {
  form: any;
  onSave: (values: any) => void;
}

export function UserCredentialsSection({ form, onSave }: UserCredentialsSectionProps) {
  return (
    <Form form={form} layout="vertical" onFinish={onSave}>
      <Card size="small" style={{ marginBottom: 16 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
          <KeyOutlined style={{ fontSize: 16, color: 'var(--hrms-primary)' }} />
          <Text strong style={{ fontSize: 14 }}>User Credentials Display</Text>
        </div>
        <Text type="secondary" style={{ fontSize: 13, display: 'block', marginBottom: 16 }}>
          Control how user login credentials are handled and displayed across the application.
        </Text>

        <Form.Item
          name={['userCredentialsConfig', 'showCredentialsInEmployeeDetail']}
          label="Show credentials in Employee Details"
          valuePropName="checked"
          extra="When enabled, the user's login email and password will be visible on the Employee Detail page."
        >
          <Switch />
        </Form.Item>

        <Form.Item
          name={['userCredentialsConfig', 'autoGeneratePasswordOnUserCreate']}
          label="Auto-generate password on user creation"
          valuePropName="checked"
          extra="When enabled, new users will have passwords auto-generated by default. Admins can still choose to set a manual password."
        >
          <Switch />
        </Form.Item>

        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 16, paddingTop: 16, borderTop: '1px solid var(--hrms-border-light)' }}>
          <Button type="primary" htmlType="submit" icon={<SaveOutlined />}>
            Save Settings
          </Button>
        </div>
      </Card>
    </Form>
  );
}
