import { ROLES } from '../../config/constants.js';
import type { Permission } from './authorize.middleware.js';

export const permissions: Record<string, Permission[]> = {
  [ROLES.SUPER_ADMIN]: [
    'manage-employees',
    'view-employees',
    'manage-departments',
    'view-departments',
    'manage-attendance',
    'manage-overtime',
    'process-payroll',
    'manage-settings',
    'manage-users',
    'view-reports',
    'view-audit',
    'manage-leave-types',
    'manage-leave-applications',
    'approve-leave',
    'view-leave',
  ],
  [ROLES.HR_ADMIN]: [
    'manage-employees',
    'view-employees',
    'manage-departments',
    'view-departments',
    'manage-attendance',
    'manage-overtime',
    'process-payroll',
    'manage-settings',
    'manage-users',
    'view-reports',
    'view-audit',
    'manage-leave-types',
    'manage-leave-applications',
    'approve-leave',
    'view-leave',
  ],
  [ROLES.HR_STAFF]: [
    'view-employees',
    'view-departments',
    'manage-attendance',
    'manage-overtime',
    'view-reports',
    'manage-leave-applications',
    'approve-leave',
    'view-leave',
  ],
  [ROLES.ACCOUNTS]: [
    'view-departments',
    'process-payroll',
    'view-reports',
    'view-leave',
  ],
  [ROLES.MANAGER]: [
    'view-departments',
    'view-reports',
    'approve-leave',
    'view-leave',
  ],
};